version: "3.2"
services:

  # tp-sh1
  tp-sh1-01:
    image: mongo:4.4.4
    container_name: tp-sh1-01
    volumes:
      - tp-sh1-01:/data/db
    expose:
    - 27011
    ports:
      - 27011:27011
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--port", "27011", "--replSet", "tp-sh1", "--shardsvr" ]
  tp-sh1-02:
    image: mongo:4.4.4
    container_name: tp-sh1-02
    volumes:
      - tp-sh1-02:/data/db
    expose:
    - 27012
    ports:
    - 27012:27012
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--port", "27012", "--replSet", "tp-sh1", "--shardsvr" ]

  # tp-sh2
  tp-sh2-01:
    image: mongo:4.4.4
    container_name: tp-sh2-01
    volumes:
      - tp-sh2-01:/data/db
    expose:
    - 27014
    ports:
      - 27014:27014
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--port", "27014", "--replSet", "tp-sh2", "--shardsvr" ]
  tp-sh2-02:
    image: mongo:4.4.4
    container_name: tp-sh2-02
    volumes:
      - tp-sh2-02:/data/db
    expose:
    - 27015
    ports:
    - 27015:27015
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--port", "27015", "--replSet", "tp-sh2", "--shardsvr" ]

  # tp-config
  tp-config-01:
    image: mongo:4.4.4
    container_name: tp-config-01
    volumes:
      - tp-config-01:/data/configdb
    expose:
    - 27017
    ports:
      - 27017:27017
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--port", "27017", "--replSet", "tp-config", "--configsvr" ]
  tp-config-02:
    image: mongo:4.4.4
    container_name: tp-config-02
    volumes:
      - tp-config-02:/data/configdb
    expose:
    - 27018
    ports:
    - 27018:27018
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--port", "27018", "--replSet", "tp-config", "--configsvr" ]

  # tp-mongos
  tp-mongos:
    image: mongo:4.4.4
    container_name: tp-mongos
    expose:
    - 27020
    ports:
      - 27020:27020
    entrypoint: [ "/usr/bin/mongos", "--bind_ip_all", "--port", "27020", "--configdb", "tp-config/tp-config-01:27017,tp-config-02:27018" ]

volumes:
  tp-sh1-01:
  tp-sh1-02:
  tp-sh2-01:
  tp-sh2-02:
  tp-config-01:
  tp-config-02: